[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test_nft = "5FYgyRz5zunLbZ4BwHR7ALzjjtRbPqr2Xe5qvDXDq4x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/biteagle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
